//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelasRegionales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telas
    {
        public int ProductoID { get; set; }
        public int TipoTelaID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }
        public Nullable<byte> Estatus { get; set; }
    
        public virtual TipoTela TipoTela { get; set; }
    }
}
