//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelasRegionales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoTela()
        {
            this.Telas = new HashSet<Telas>();
        }
    
        public int TipoTelaID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telas> Telas { get; set; }
    }
}
